# fly.toml app configuration file generated for full-stack-open-part11-pokedex on 2023-12-22T07:57:57-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "full-stack-open-part11-pokedex"
primary_region = "scl"

[processes]
  app = "node app.js"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "npm run build"

[build]
  [build.args]
    NODE_VERSION = "16.19.0"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]